### ISSUE TITLE
Deposit

### ISSUE THREAD

**Issue by KarboXXX** [ikafly144/EmeraldBank#3]
Can only deposit to bank account if i have admin permission, emeraldbank.banking.deposit true does not have any effects.
When depositing, the bank account balance increases, but the emeralds on inventory are not cleared

**Comment by ikafly144** [comment]
I was unable to reproduce this phenomenon. Try using the latest version.
`emeraldbank.banking.deposit` is the default permission, so by setting `emeraldbank.banking.deposit` to `false` you will prevent players from depositing money.
